project_id = "snwuzldwstggcnlhiifi"

[functions.submit-payment-proof]
verify_jwt = false

[functions.telegram-webhook]
verify_jwt = false

[functions.get-order-status]
verify_jwt = false

[functions.send-key-email]
verify_jwt = false